### POST Test Result
POST http://localhost:3000/api/test/save_test
Content-Type: application/json

{
  "index": 2
}



### Fetch Test By Index
GET http://localhost:3000/api/test/get_test/2
Content-Type: application/json