### Create Report
GET http://localhost:3000/api/test/save_test
Content-Type: application/json

{
  "id": "Checking api",
  "pw": "1234"
}
### Test
GET http://localhost:3000/api/test/get_test
Content-Type: application/json

{
  "index": 2
}
