### Create User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "hehe@eee.com",
  "password": "jjejejei22"
}

### Find One
GET http://localhost:3000/auth/122
Content-Type: application/json

### Find All Users with a given Email
GET http://localhost:3000/auth?email=hehe@eee.com
Content-Type: application/json


### Delete User
DELETE http://localhost:3000/auth/3
Content-Type: application/json


### Update One User
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
  "email": "Hyunsoo@gmail.com"
}