### Create User (Sign Up)
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345"
}

### Sign In
GET http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345"
}
### Sign Out
POST http://localhost:3000/auth/signout
Content-Type: application/json


### Get the currently signed is users
GET http://localhost:3000/auth/whoami
Content-Type: application/json


### Find One
GET http://localhost:3000/auth/1
Content-Type: application/json

### Find All Users with a given Email
GET http://localhost:3000/auth?email=hehe@eee.com
Content-Type: application/json


### Delete User
DELETE http://localhost:3000/auth/3
Content-Type: application/json


### Update One User
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
  "email": "Hyunsoo@gmail.com"
}